version: 2.1

orbs:
  tholos: cryptomove/cryptomove@0.0.2

jobs:
  test:
    docker:
      - image: circleci/ruby:latest

    steps:
      - checkout
      - tholos/install
      - tholos/run_command:
          step-name: Is the secret sauce marinara?
          command: >
            ruby -e "ENV['SECRET_SAUCE'] == 'marinara' ? true : fail"
