version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Is the secret sauce marinara?
          command: $SECRET_SAUCE == "marinara"
