version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:latest

    steps:
      - checkout

      - run:
          name: Is the secret sauce marinara?
          command: >
            ruby -e "ENV['SECRET_SAUCE'] == 'marinara' ? true : fail"
