version: 2.1

orbs:
  tholos: cryptomove/cryptomove@0.0.2

jobs:
  build:
    docker:
      - image: circleci/ruby:latest

    steps:
      - checkout
      - tholos/install
      - tholos/run_command:
          step-name: Is the secret sauce marinara?
          command: >
            ruby -e "`echo $SECRET_SAUCE` == %Q{marinara} ? true : fail"
